## 1. Split this string


In [ ]:
s = "Hi there Sam!"

In [ ]:
a = s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of {} is {} kilometers.'.format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
zeroes = np.zeros(10)
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
new_arr=np.arange(20,35,2)
print(new_arr)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
mat =  np.arange(0, 9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
C = np.concatenate((a, b), axis = None)
print(C)

[1 2 3 4 5 6]


# Pandas

In [ ]:
import pandas as pd

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
data = [['Abel', 10], ['Bob', 9], ['Alex', 17]]
defn = pd.DataFrame(data, columns=['Name', 'Age'])
defn

Name  Age
0  Abel   10
1   Bob    9
2  Alex   17

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
d=pd.date_range(start='01/01/2023', end='02/10/2023')
for i in d:
  print(i.date())

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
li = [['ramesh', 'suresh', 20], ['krishna', 'Bob', 32],
	['sriram', 'henry', 29], ['alex', 'sandy', 21]]
	
defn = pd.DataFrame(li, columns =['FirstName', 'LastName', 'Age'])
print(defn)

  FirstName LastName  Age
0    ramesh   suresh   20
1   krishna      Bob   32
2    sriram    henry   29
3      alex    sandy   21
